services:
  - type: web
    name: cms-backend
    runtime: node
    rootDir: cms
    buildCommand: npm install && npm run build
    startCommand: npm run start

  - type: web
    name: gallery-frontend
    runtime: static
    rootDir: gallery
    buildCommand: npm install && npm run build
    startCommand: npm run start
    staticPublishPath: ./.next
    buildFilter:
      paths:
        - gallery/**/*.js
        - gallery/**/*.css
      ignoredPaths:
        - gallery/**/*.test.js
